### PR TITLE
Increase color contrast

### PR DESCRIPTION
**Pull request by wlonk**
And fix top nav.

See #43.

kitten

### CODE REVIEW

**Comment by wlonk** [comment]
@mirisuzanne I'd love if you could take a look at this. In particular:

- [ ] Is the color scheme terrible? I don't trust myself to tell. It's higher-contrast than the previous one, which improves our a11y scores.
- [ ] Is the Sass structured poorly? Are there improvements I could make there?

**Comment by wlonk** [comment]
@mirisuzanne I'd appreciate that if you have time and interest.

**Comment by mirisuzanne** [comment]
@wlonk see what you think. I don't know Bootstrap well, but I used a combination of https://contrast-ratio.com/ to test a11y, and http://scg.ar-ch.org/ to find darker versions of colors – and I think things are generally looking more readable.

**Comment by wlonk** [comment]
@mirisuzanne you're a gol-dang genius, I love these colors. They harmonize, look rich and inviting. Everything is better. Merging.

**Pull request merged**
