### PR TITLE
Update entries in yarn.lock

### PR DESCRIPTION
**Pull request by wlonk**
Just that.

### CODE REVIEW

**Comment by ojacobson** [comment]
I really want a way to summarize the changes in the affected libraries, without having to go through and review each library's changelog (or worse, each library's commit history) individually. I'm sure this was fine, and I'm reasonably sure that either testing or user activity will reveal any significant compatibility or behavioural changes, but it feels bad to drop 1k lines of library update with no explanation for why beyond the perspective that _not_ updating is a worse risk.

**Comment by wlonk** [comment]
Yeah, welcome to JSlandia :-/

**Comment by ojacobson** [comment]
I have this problem in Rust, and in Python, as well. I assume it affects Ruby and Go, although I have less direct experience with it. I'm disinclined to write this off as a JS-specific phenomenon, personally, although I appreciate where that comes from.

**Comment by wlonk** [comment]
What's very JS-y about it is the depth and opacity of the dependency tree, in my view. The general issue is general, though.

**Pull request merged**
